### ISSUE TITLE
Allow PluginFactory to use a different Plugin class

### ISSUE THREAD

**Issue by GaryJones** [cedaro/wp-plugin#2]
I want to try and combine this `wp-plugin` with my previous setup, which uses a config-based approach. For that, I pass in a Config object to my [`Plugin` constructor](https://github.com/GaryJones/plugin-boilerplate/blob/cfeffab9f3a5493c84722bb5921f84972524235b/src/Plugin.php#L53).

I can make my `Plugin` become ` class Plugin extends \Cedaro\WP\Plugin\Plugin` so that I can benefit from the `set_*()` methods, but I'd still need to also extend the `PluginFactory` so that it called my version of the plugin.

Could `PluginFactory` be made extensible, so that I could say which `Plugin` class to instantiate? (i.e. mine, which extends yours)?

**Comment by bradyvercher** [comment]
I mainly added the factory as a convenience method for instantiating a plugin with the most common defaults, but don't use it much myself. If you've got a suggestion for refactoring the approach here, I'm fine with that, but backward compatibility needs to be considered carefully since it's easy to create conflicts when multiple plugins depend on different versions.

Otherwise, instead of extending the factory, you could create your own that does what you need or just instantiate and configure the plugin object directly.

**Comment by GaryJones** [comment]
Thanks - if the use of the PluginFactory isn't a key criteria, I'll configure the plugin object directly (like SatisPress does).
